// <auto-generated />
namespace BaseWebApp.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class UserAccountId : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(UserAccountId));
        
        string IMigrationMetadata.Id
        {
            get { return "201911181443305_UserAccountId"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
